ionos-cloud/module-ansible

- .github/workflows/CI.yml
- .github/workflows/Publish.yml
- docs/changelog.md
- galaxy.yml
- plugins/modules/volume.py
- tests/attach-volume-test.yml
- tests/vars.yml
Fix #2 - fixed the attachment of a volume to a server
> Fix #2 attach volume to server

- .github/workflows/CI.yml
- docs/changelog.md
- galaxy.yml
- plugins/modules/nic.py
- plugins/modules/server.py
> Fix: fix server (#15) and nic bugs

- .github/workflows/CI.yml
- docs/api/group.md
- docs/changelog.md
- galaxy.yml
- plugins/modules/group.py
- tests/group-test.yml
> feat: improve group permissions

- docs/usage/ansibleplaybooks.md
- docs/usage/sshkeyauthentication.md
- plugins/modules/server.py
Make name of the module explicit in the examples
> Fix docs - name of the module

- docs/api/managed-kubernetes/k8scluster.md
fixed some field names and requirements
> fix k8s docs

- .github/workflows/CI.yml
Add paths conditions to CI workflow.
> fix: update workflow trigger conditions

- .github/workflows/CI.yml
Add paths conditions to CI workflow.
> fix: update workflow trigger conditions v6

- .github/workflows/CI.yml
- .github/workflows/Publish.yml
- docs/api/managed-kubernetes/k8scluster.md
- docs/api/managed-kubernetes/k8snodepool.md
- plugins/modules/k8s_cluster.py
- plugins/modules/k8s_nodepool.py
- tests/postgres-cluster-test.yml
- tests/private-k8s-cluster-test.yml
- tests/vars.yml
- implemented private k8s cluster feature
- new params on k8s_cluster: api_subnet_allow_list, public, s3_buckets
- new params on k8s_cluster_nodepool: gateway_ip
- new test for private k8s cluster
> feat: private k8s [WIP]

- docs/api/managed-kubernetes/k8snodepool.md
fixes https://github.com/ionos-cloud/module-ansible/issues/58
fixes https://github.com/ionos-cloud/module-ansible/issues/53
and fixes some other things working different than the docs explained so far.
> fix the docs of k8s_nodepools

- .github/workflows/CI.yml
- README.md
- docs/changelog.md
- galaxy.yml
- plugins/modules/server.py
Fix STOP server bug: the resources are now deallocated when a shut-off server is stopped.
> fix: fix STOP server bug v5

- .github/workflows/CI.yml
- README.md
- docs/changelog.md
- galaxy.yml
- plugins/modules/server.py
- tests/k8s-cluster-nodepool-test.yml
- tests/k8s-cluster-test.yml
- tests/private-k8s-cluster-test.yml
- tests/vars.yml
Fix STOP server bug: the resources are now deallocated when a shut-off server is stopped.
> fix: fix STOP server bug

- docs/usage/authentication.md
- plugins/modules/backupunit.py
- plugins/modules/datacenter.py
- plugins/modules/firewall_rule.py
- plugins/modules/group.py
- plugins/modules/image.py
- plugins/modules/ipblock.py
- plugins/modules/k8s_cluster.py
- plugins/modules/k8s_config.py
- plugins/modules/k8s_nodepool.py
- plugins/modules/lan.py
- plugins/modules/nic.py
- plugins/modules/pcc.py
- plugins/modules/s3key.py
- plugins/modules/server.py
- plugins/modules/share.py
- plugins/modules/snapshot.py
- plugins/modules/user.py
- plugins/modules/volume.py
#63
(v5 branch)
If token provided, use token authentication instead of username & password.
> Feat: v5 - Token authentication if possible

- docs/api/managed-kubernetes/k8s_nodepool.md
- plugins/modules/k8s_nodepool.py
- tests/managed-kubernetes/k8s-cluster-nodepool-test.yml
- tests/managed-kubernetes/private-k8s-cluster-test.yml
- tests/vars.yml
Add option to update labels and annotations on k8s nodepools.
> feat: add update for labels and annotations on k8s nodepools

- .github/workflows/CI.yml
- .github/workflows/Publish.yml
- docs/api/networkloadbalancer/network_load_balancer_rule.md
- plugins/modules/network_load_balancer_rule.py
- tests/networkloadbalancer/network-load-balancer-rule-test.yml
Fix NLB health_check dict parameter.
> fix: fix nlb health_check param

- docs/changelog.md
- docs/usage/http_proxy.md
- galaxy.yml
Update README and CHANGELOG to reflect the changes from the 6.1.3 release.
> docs: update documentation for v6.1.3 release

- docs/changelog.md
- docs/summary.md
- docs/usage/http_proxy.md
Update README and CHANGELOG to reflect the changes from the 5.0.11 release.
> docs: update documentation for upcoming release

- plugins/modules/k8s_cluster.py
- plugins/modules/k8s_nodepool.py
these params were removed in 6.0.4 python sdk release
> fix: remove public, gateway_ip params for k8s

- .github/scripts/string_in_array.sh
- .github/workflows/CI.yml
https://github.com/jitterbit/get-changed-files
> test: skip k8s tests if haven't modified any k8s file

- README.md
- docs/README.md
- docs/api/dbaas-postgres/postgres_cluster.md
- plugins/modules/postgres_cluster.py
- tests/dbaas-postgres/postgres-cluster-test.yml
Add new values for DBaaS postgres clusters storage types.
> feat: [DBaaS] add new SSD storage types

- plugins/inventory/inventory.ini
- plugins/inventory/inventory.py
fixes https://github.com/ionos-cloud/module-ansible/issues/26 and https://github.com/ionos-cloud/module-ansible/issues/27
> fix: inventory output json and working script

- .github/workflows/CI.yml
- .github/workflows/Publish.yml
Make CI workflow inherit all secrets from Publish workflow when triggered by calling.
Also remove unused input on CI workflow.
> fix: publish workflow

- docs/api/compute-engine/nic.md
- plugins/modules/image.py
- plugins/modules/nic.py
- fix module args indentation
- add `name` for each task
> doc: Fix module indentation for nic and image

- docs/api/compute-engine/image.md
- docs/api/compute-engine/nic.md
- docs/api/managed-kubernetes/k8s_nodepool.md
- plugins/modules/k8s_nodepool.py
- tests/managed-kubernetes/nodepool/k8s-cluster-nodepool-test.yml
> doc: changed nodepool node_count example, regenerated docs

- plugins/modules/nic.py
- plugins/modules/postgres_cluster.py
- tests/dbaas-postgres/postgres-cluster-test.yml
> feat: declarative postgres_cluster

- docs/api/managed-backup/backupunit.md
- docs/api/natgateway/nat_gateway.md
- docs/api/natgateway/nat_gateway_flowlog.md
- docs/api/natgateway/nat_gateway_rule.md
- docs/api/networkloadbalancer/network_load_balancer.md
- docs/api/networkloadbalancer/network_load_balancer_flowlog.md
- docs/api/networkloadbalancer/network_load_balancer_rule.md
- plugins/modules/backupunit.py
- tests/managed-backup/backupunit-test.yml
> Declarative backupunit

- docs/api/applicationloadbalancer/application_load_balancer.md
- docs/api/applicationloadbalancer/application_load_balancer_flowlog.md
- docs/api/applicationloadbalancer/application_load_balancer_forwardingrule.md
- plugins/modules/application_load_balancer.py
- plugins/modules/application_load_balancer_flowlog.py
- plugins/modules/application_load_balancer_forwardingrule.py
- plugins/modules/network_load_balancer_flowlog.py
- plugins/modules/network_load_balancer_rule.py
- plugins/modules/target_group.py
- tests/application-loadbalancers/application-load-balancer-flowlog-test.yml
- tests/application-loadbalancers/application-load-balancer-forwardingrule-test.yml
- tests/application-loadbalancers/application-load-balancer-test.yml
- tests/application-loadbalancers/target-group-test.yml
> Declarative alb

- .github/workflows/CI.yml
> fix: CI python version

- docs/summary.md
> docs: add new products to Gitbook

- plugins/modules/mongo_cluster_user.py
- tests/dbaas-mongo/mongo-cluster-test.yml
> fix: mongo tests

- docs/changelog.md
- plugins/modules/k8s_cluster.py
- tests/managed-kubernetes/cluster/k8s-cluster-test.yml
- tests/managed-kubernetes/cluster/private-k8s-cluster-test.yml
- tests/managed-kubernetes/nodepool/k8s-cluster-nodepool-test.yml
> fix: k8s version in tests

- docs/api/container-registry/registry.md
- docs/api/container-registry/registry_info.md
- docs/api/container-registry/registry_token.md
- docs/api/container-registry/registry_token_info.md
- plugins/modules/registry.py
- plugins/modules/registry_info.py
- plugins/modules/registry_token.py
- plugins/modules/registry_token_info.py
> feat: implement filters for CR info modules

- docs/api/applicationloadbalancer/application_load_balancer.md
- docs/api/applicationloadbalancer/application_load_balancer_flowlog.md
- docs/api/applicationloadbalancer/application_load_balancer_forwardingrule.md
- docs/api/applicationloadbalancer/target_group.md
- docs/api/container-registry/registry.md
- docs/api/container-registry/registry_token.md
- plugins/modules/registry.py
- plugins/modules/registry_token.py
- tests/container-registry/registry-test.yml
- tests/container-registry/registry-token-test.yml
> Declarative container registry

- docs/api/natgateway/nat_gateway.md
- docs/api/natgateway/nat_gateway_flowlog.md
- docs/api/natgateway/nat_gateway_rule.md
- docs/api/networkloadbalancer/network_load_balancer.md
- docs/api/networkloadbalancer/network_load_balancer_flowlog.md
- docs/api/networkloadbalancer/network_load_balancer_rule.md
- docs/api/user-management/group.md
- docs/api/user-management/s3key.md
- docs/api/user-management/user.md
- plugins/modules/group.py
- plugins/modules/s3key.py
- plugins/modules/share.py
- plugins/modules/user.py
- tests/user-management/group-test.yml
- tests/user-management/s3key-test.yml
- tests/user-management/share-test.yml
- tests/user-management/user-test.yml
> Declarative user management

- docs/changelog.md
- galaxy.yml
> docs: release v6.5.0

- docs/api/certificate/certificate.md
- plugins/modules/certificate.py
- tests/certificate-manager/certificate-test.yml
> feat: declarative certificate

- README.md
> docs: add new dependencies

- tests/application-loadbalancers/all-tests.yml
- tests/compute-engine/all-tests.yml
- tests/natgateway/all-tests.yml
- tests/networkloadbalancer/all-tests.yml
> fix: remove tests

- docs/changelog.md
- galaxy.yml
> docs: documentation for release v6.5.3

- docs/usage/declarative_changes.md
> docs: suggestions for declarative documentation

- plugins/modules/group.py
- plugins/modules/s3key.py
- plugins/modules/s3key_info.py
- plugins/modules/user.py
> fix: use pagination to retrieve users

- docs/api/managed-kubernetes/k8s_config.md
- plugins/modules/k8s_config.py
- plugins/modules/mongo_cluster_template_info.py
- plugins/modules/nic_flowlog.py
- tests/compute-engine/nic-flowlog-test.yml
- tests/dbaas-mongo/mongo-cluster-test.yml
- tests/managed-kubernetes/cluster/k8s-cluster-test.yml
> fix: fix wrong depth, wrong api

- docs/api/dbaas-mongo/mongo_cluster.md
- plugins/modules/backupunit.py
- plugins/modules/mongo_cluster.py
- plugins/modules/registry.py
- plugins/modules/registry_token.py
- plugins/modules/volume.py
- tests/certificate-manager/certificate-test.yml
- tests/compute-engine/cube-server-test.yml
- tests/compute-engine/datacenter-test.yml
- tests/compute-engine/ipblock-test.yml
- tests/compute-engine/volume-test.yml
- tests/container-registry/registry-test.yml
- tests/container-registry/registry-token-test.yml
- tests/dataplatform/dataplatform-test.yml
- tests/dataplatform/vars.yml
- tests/dbaas-mongo/mongo-cluster-test.yml
- tests/dbaas-postgres/postgres-cluster-test.yml
- tests/managed-backup/backupunit-test.yml
- tests/managed-kubernetes/nodepool/k8s-cluster-nodepool-test.yml
> Improve tests

- plugins/modules/mongo_cluster_template_info.py
- tests/dbaas-mongo/all-tests.yml
- tests/dbaas-mongo/mongo-cluster-template-info-test.yml
> Fix mongo template

- docs/api/compute-engine/datacenter.md
- docs/api/compute-engine/nic.md
- plugins/modules/datacenter.py
> chore: add missing datacenter location, regenerated docs

- .github/workflows/cleanup.yml
> added cleanup workflow

- docs/api/compute-engine/cube_server.md
- plugins/modules/cube_server.py
> changed disk_type default value to DAS for cube_server

- plugins/modules/cube_server.py
- plugins/modules/server.py
- plugins/modules/vcpu_server.py
- plugins/modules/volume.py
> fix: mark RegEx pattern as a raw string

- docs/api/user-management/group.md
- docs/api/user-management/user.md
- plugins/modules/group.py
- plugins/modules/user.py
- tests/user-management/s3key-test.yml
- tests/user-management/user-test.yml
> feat: added ignored_properties to user

- docs/api/user-management/group.md
- docs/api/user-management/user.md
- docs/changelog.md
- docs/summary.md
- docs/templates/summary.mustache
- docs/usage/check_mode_and_diff.md
- galaxy.yml
- plugins/module_utils/common_ionos_methods.py
- plugins/module_utils/common_ionos_module.py
- plugins/modules/cube_server.py
- plugins/modules/group.py
- plugins/modules/group_info.py
- plugins/modules/s3key.py
- plugins/modules/s3key_info.py
- plugins/modules/server.py
- plugins/modules/user.py
- plugins/modules/user_info.py
- plugins/modules/vcpu_server.py
- plugins/modules/volume.py
- reset.sh
- tests/user-management/group-test.yml
- tests/user-management/s3key-test.yml
- tests/user-management/user-test.yml
> New release

- README.md
> chore: remove basic auth deprecation notice from readme

- .github/workflows/CI.yml
- .github/workflows/cleanup.yml
- plugins/module_utils/common_ionos_methods.py
- plugins/modules/volume.py
- plugins/modules/volume_info.py
- tests/compute-engine/vars.yml
- tests/compute-engine/volume-test.yml
> fix: throw error when dc is not found in volume modules

- plugins/module_utils/common_ionos_methods.py
> fix: reduce size of error message

- docs/changelog.md
- galaxy.yml
> doc: updated changelog and version

- docs/api/compute-engine/cube_server.md
- docs/api/compute-engine/server.md
- docs/api/compute-engine/server_info.md
- docs/api/dataplatform/dataplatform_cluster.md
- docs/api/managed-kubernetes/k8s_nodepool.md
- docs/api/vm-autoscaling/vm_autoscaling_group.md
- docs/changelog.md
- galaxy.yml
- plugins/modules/cube_server.py
- plugins/modules/dataplatform_cluster.py
- plugins/modules/k8s_nodepool.py
- plugins/modules/server.py
- plugins/modules/server_info.py
- plugins/modules/vm_autoscaling_group.py
- reset.sh
- tests/compute-engine/server-test.yml
- tests/compute-engine/vcpu-server-test.yml
> fix: remove upgrade_needed from server_info

- docs/changelog.md
- plugins/modules/cube_server.py
- plugins/modules/vcpu_server.py
> fix: use correct imports for lan and lan properties

- docs/api/compute-engine/server.md
- docs/changelog.md
- plugins/modules/datacenter.py
- plugins/modules/server.py
- plugins/modules/snapshot.py
- tests/compute-engine/ipv6-test.yml
> fix: fix snapshot creating based on changes in sdk 6.1.10
